apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: nukg-website
spec:                
  selector:         
    matchLabels:
      app: nukg-website
  replicas: 2
  template:
    metadata:
      name: nukg-website
      labels:        
        app: nukg-website
    spec:
      containers:
        - name: nukg-website
          image: 416175598939.dkr.ecr.us-east-1.amazonaws.com/nukg-website:latest
          ports:
            - containerPort: 8080

