apiVersion: v1
kind: Service
metadata:
  name: nukg-website
  labels:
    app: nukg-website
spec:
  ports:
    - name : nukg-website
      port: 80
      targetPort: 8080  
      protocol: TCP
  selector:
    app: nukg-website
  type: LoadBalancer

